"""print orientation, layer height and note for every printed part - shared by export.py and printcheck.py"""
from model import *
PRINT = {
    "knob_body":          (lambda s: Pos(0, 0, Z_KNOB_TOP) * Rot(180, 0, 0) * s, "0.16", "ONE PIECE. top face down, no supports (the relief band's 0.3 step is a single perimeter's overhang - printcheck counts its 167 mm2). bore smooth except the V-RIDGE on its relief band (v16: a 1.2 tall 90 deg ridge at z 19.9-23.1 - printed top-down its lower flank is a 45 deg overhang, fine); the 0.15 code-ring recess is in the crown's underside (the bed face, so it prints as a shallow pocket)"),
    "internal_structure": (lambda s: Pos(0, 0, Z_SEAT_TOP) * Rot(180, 0, 0) * s, "0.20", "v16: INVERTED as v15 - the seat flange's top face on the bed, the wall growing up from it (its 50 deg ramp outward at z 13.8-16.2 self-supports), the wall foot at the top. SUPPORTS: the halo ledge + lip (a 6.3-wide ring hanging outward at z 13.2-14.3 - removable, the face it marks is under the knob skirt) and the two Ø8 fixed-post tops (z 19.0). The block channel's roof (8.4 wide) is a bridge; its walls and end wall print up from it. The pillar tops and the LRA clip ribs carry 45 deg cones/webs; the windows are open at the bed; 0.3 chamfers on the bed face's edges"),
    "halo_liner":         (lambda s: Pos(0, 0, -Z_PLATE_TOP) * s, "0.16", "v16: WHITE PETG, flat on its floor face; the 0.6 wall stands up; no supports. Cut at the two tail notches"),
    "wheel_block":        (lambda s: Pos(0, 0, -Z_BLOCK0) * s, "0.12", "v16: flat on its bottom face; the Ø2.9 pin hole vertical; the spring pocket and the M2 insert hole are side holes (Ø4.2 / Ø3.2 - small, print as drawn); PETG, 4 perimeters"),
    "drive_collar":       (lambda s: Pos(0, 0, -Z_COLLAR0) * s, "0.12", "v16: axis vertical, the lead-in chamfer at the bottom; press over the bell's top 3.5 (ID 35 -0.05); PETG (prototype) / POM (production)"),
    "mcu_tray":           (lambda s: Pos(0, 0, -Z_TRAY0) * s, "0.16", "v16: flat on its underside; the MCU pocket is a 0.6 recess in the top; four Ø2.2 holes"),
    "tray_keeper":        (lambda s: Pos(0, 0, -Z_TRAY1) * s, "0.16", "v16: flat; a frame with a window over the MCU's parts; four Ø2.2 holes"),
    "board_spacer":       (lambda s: s, "0.12", "v16: a FAMILY - Ø5 tubes, bore 2.2: 3.0 (x6, under the driver, haptic and level-shifter breakouts), 1.0 (x4, under the audio board), 4.4 (x4, between the audio's nuts and the tray); axis vertical"),
    "carriage":           (lambda s: s, "0.16", "standing on the Ø37 shoe, tab up; 12 mm bridge over the sensor pocket; PETG, 4 perimeters (the tab is loaded across its layers)"),
    "servo_mount":        (lambda s: s, "0.20", "flat; a floorless frame for the AGFRC servo, open toward the tab; two ears screwed to the plate"),
    "connect_bracket":    (lambda s: Rot(90, 0, 0) * s, "0.20", "standing on its straight -y edge, the slab vertical (1.5 thick, 28 wide, 50 tall): the feet, ears and bosses stick out sideways and print without support; the M2 insert holes and the csk cones are sideways at Ø3.2 / Ø5.4, fine at that size. (On its feet the slab would hang 1.5 over the bed for 28 mm: supports)"),
    "speaker_cradle":     (lambda s: s, "0.20", "flat; ring under the speaker flange with three snap fingers"),
    "blower_saddle":      (lambda s: Pos(0, 0, Z_BLOWER1 + SADDLE_T) * Rot(180, 0, 0) * s, "0.16", "v15: on its flat top face (the motion board's face) on the bed, the hood's neck walls grow up from it; no supports. Two Ø2.2 through-holes vertical"),
    "hood_lid":           (lambda s: Pos(0, 0, -(PLATE_T + BLOWER_GASKET_T)) * s, "0.16", "v15: flat, 2.5 thick, two Ø2.2 holes; butts against the saddle's neck"),
    "encoder_shim":       (lambda s: Pos(0, 0, -Z_SEAT_TOP) * s, "0.10", "v15: flat, one per height in ENC_SHIM_FAMILY (0.7 / 0.8 / 0.9 / 1.0 / 1.1) - print the set, fit the one the bench wants"),
    "port_face":          (lambda s: Pos(0, 0, PORT_FACE_R0 + PORT_FACE_T) * Rot(0, 90, 0) * s, "0.16", "lying on its outer face (the socket openings print as vertical holes); the USB-C shelf, the light-sensor foot and the screw rail stand up from it; no supports"),
}
